<?php
declare(strict_types=1);

$wellPhoto = '/images/wells/recharge-well-placeholder.png';

$wells = [
    [
        'id' => 'RW-01',
        'deviceId' => 'device_1',
        'name' => 'Ubud Area 1',
        'city' => 'Ubud',
        'lat' => -8.5069,
        'lng' => 115.2625,
        'status' => 'online',
        'statusLabel' => 'Online',
        'startDate' => '23 April 2026',
        'startDateISO' => '2026-04-23',
        'endDate' => '26 July 2026',
        'endDateISO' => '2026-07-26',
        'duration' => '1 Month',
        'absorption' => '5 ml',
        'transmission' => 'Strong',
        'lastTransmission' => '10 min ago',
        'wellType' => '4',
        'litresMinute' => '2 m³/min',
        'litresHour' => '8 litres per hour',
        'volume' => '20,933 L',
        'inflow' => '4.0 m³/hr',
        'x' => 52,
        'y' => 61,
        'photo' => $wellPhoto,
        'locationPending' => true,
    ],
    [
        'id' => 'RW-07',
        'name' => 'Tabanan Area 1',
        'city' => 'Tabanan',
        'lat' => -8.5433,
        'lng' => 115.125,
        'status' => 'online',
        'statusLabel' => 'Online',
        'startDate' => '29 April 2026',
        'startDateISO' => '2026-04-29',
        'endDate' => '26 July 2026',
        'endDateISO' => '2026-07-26',
        'duration' => '1 Month',
        'absorption' => '5 ml',
        'transmission' => 'Strong',
        'lastTransmission' => '20 min ago',
        'wellType' => '3',
        'litresMinute' => '1.8 m³/min',
        'litresHour' => '7 litres per hour',
        'volume' => '18,670 L',
        'inflow' => '3.6 m³/hr',
        'x' => 40,
        'y' => 67,
        'photo' => $wellPhoto,
    ],
];
