<?php
declare(strict_types=1);

$wellPhoto = '/images/wells/recharge-well-placeholder.png';

$wells = [
    [
        'id' => 'RW-01',
        'name' => 'Ubud Area 1',
        'city' => 'Ubud',
        'status' => 'online',
        'statusLabel' => 'Online',
        'startDate' => '23 April 2026',
        'endDate' => '26 July 2026',
        'duration' => '1 Month',
        'absorption' => '5 ml',
        'transmission' => 'Strong',
        'lastTransmission' => '10 min ago',
        'wellType' => '4',
        'litresMinute' => '2 m³/min',
        'litresHour' => '8 litres per hour',
        'volume' => '20,933 L',
        'inflow' => '4.0 m³/hr',
        'x' => 52,
        'y' => 61,
        'photo' => $wellPhoto,
    ],
    [
        'id' => 'RW-07',
        'name' => 'Tabanan Area 1',
        'city' => 'Tabanan',
        'status' => 'online',
        'statusLabel' => 'Online',
        'startDate' => '29 April 2026',
        'endDate' => '26 July 2026',
        'duration' => '1 Month',
        'absorption' => '5 ml',
        'transmission' => 'Strong',
        'lastTransmission' => '20 min ago',
        'wellType' => '3',
        'litresMinute' => '1.8 m³/min',
        'litresHour' => '7 litres per hour',
        'volume' => '18,670 L',
        'inflow' => '3.6 m³/hr',
        'x' => 40,
        'y' => 67,
        'photo' => $wellPhoto,
    ],
    [
        'id' => 'RW-12',
        'name' => 'Denpasar Area 1',
        'city' => 'Denpasar',
        'status' => 'offline',
        'statusLabel' => 'Offline',
        'startDate' => '15 May 2026',
        'endDate' => '15 July 2026',
        'duration' => '1 Month',
        'absorption' => '5 ml',
        'transmission' => 'No Signal',
        'lastTransmission' => '2 hours ago',
        'wellType' => '4',
        'litresMinute' => '2 m³/min',
        'litresHour' => '8 litres per hour',
        'volume' => '19,280 L',
        'inflow' => '3.8 m³/hr',
        'x' => 47,
        'y' => 82,
        'photo' => $wellPhoto,
    ],
    [
        'id' => 'RW-18',
        'name' => 'Gianyar Area 1',
        'city' => 'Gianyar',
        'status' => 'online',
        'statusLabel' => 'Online',
        'startDate' => '15 May 2026',
        'endDate' => '26 July 2026',
        'duration' => '1 Month',
        'absorption' => '5 ml',
        'transmission' => 'Strong',
        'lastTransmission' => '1 hour ago',
        'wellType' => '3',
        'litresMinute' => '2.1 m³/min',
        'litresHour' => '8 litres per hour',
        'volume' => '20,933 L',
        'inflow' => '4.0 m³/hr',
        'x' => 61,
        'y' => 74,
        'photo' => $wellPhoto,
    ],
    [
        'id' => 'RW-23',
        'name' => 'Badung Area 1',
        'city' => 'Badung',
        'status' => 'no-signal',
        'statusLabel' => 'No Signal',
        'startDate' => '15 May 2026',
        'endDate' => '26 July 2026',
        'duration' => '1 Month',
        'absorption' => '5 ml',
        'transmission' => 'No Signal',
        'lastTransmission' => '1 day ago',
        'wellType' => '4',
        'litresMinute' => '2.2 m³/min',
        'litresHour' => '9 litres per hour',
        'volume' => '22,105 L',
        'inflow' => '4.2 m³/hr',
        'x' => 45,
        'y' => 47,
        'photo' => $wellPhoto,
    ],
    [
        'id' => 'RW-31',
        'name' => 'Jembrana Area 1',
        'city' => 'Jembrana',
        'status' => 'online',
        'statusLabel' => 'Online',
        'startDate' => '01 June 2026',
        'endDate' => '01 August 2026',
        'duration' => '2 Months',
        'absorption' => '6 ml',
        'transmission' => 'Strong',
        'lastTransmission' => '12 min ago',
        'wellType' => '3',
        'litresMinute' => '2.4 m³/min',
        'litresHour' => '9 litres per hour',
        'volume' => '23,840 L',
        'inflow' => '4.5 m³/hr',
        'x' => 23,
        'y' => 56,
        'photo' => $wellPhoto,
    ],
    [
        'id' => 'RW-42',
        'name' => 'Buleleng Area 1',
        'city' => 'Buleleng',
        'status' => 'offline',
        'statusLabel' => 'Offline',
        'startDate' => '10 June 2026',
        'endDate' => '10 August 2026',
        'duration' => '2 Months',
        'absorption' => '4 ml',
        'transmission' => 'Weak',
        'lastTransmission' => '6 hours ago',
        'wellType' => '3',
        'litresMinute' => '1.7 m³/min',
        'litresHour' => '6 litres per hour',
        'volume' => '16,420 L',
        'inflow' => '3.1 m³/hr',
        'x' => 55,
        'y' => 25,
        'photo' => $wellPhoto,
    ],
    [
        'id' => 'RW-55',
        'name' => 'Bangli Area 1',
        'city' => 'Bangli',
        'status' => 'no-signal',
        'statusLabel' => 'No Signal',
        'startDate' => '15 June 2026',
        'endDate' => '15 August 2026',
        'duration' => '2 Months',
        'absorption' => '5 ml',
        'transmission' => 'No Signal',
        'lastTransmission' => '2 days ago',
        'wellType' => '4',
        'litresMinute' => '2 m³/min',
        'litresHour' => '8 litres per hour',
        'volume' => '20,010 L',
        'inflow' => '3.9 m³/hr',
        'x' => 66,
        'y' => 43,
        'photo' => $wellPhoto,
    ],
    [
        'id' => 'RW-63',
        'name' => 'Karangasem Area 1',
        'city' => 'Karangasem',
        'status' => 'offline',
        'statusLabel' => 'Offline',
        'startDate' => '20 June 2026',
        'endDate' => '20 August 2026',
        'duration' => '2 Months',
        'absorption' => '4 ml',
        'transmission' => 'Weak',
        'lastTransmission' => '4 hours ago',
        'wellType' => '3',
        'litresMinute' => '1.9 m³/min',
        'litresHour' => '7 litres per hour',
        'volume' => '17,930 L',
        'inflow' => '3.4 m³/hr',
        'x' => 77,
        'y' => 56,
        'photo' => $wellPhoto,
    ],
    [
        'id' => 'RW-76',
        'name' => 'Klungkung Area 1',
        'city' => 'Klungkung',
        'status' => 'online',
        'statusLabel' => 'Online',
        'startDate' => '20 June 2026',
        'endDate' => '20 August 2026',
        'duration' => '2 Months',
        'absorption' => '5 ml',
        'transmission' => 'Strong',
        'lastTransmission' => '25 min ago',
        'wellType' => '4',
        'litresMinute' => '2.3 m³/min',
        'litresHour' => '9 litres per hour',
        'volume' => '22,640 L',
        'inflow' => '4.3 m³/hr',
        'x' => 70,
        'y' => 68,
        'photo' => $wellPhoto,
    ],
];
